// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQlqUciBbKX8xb506OGBzarNOz6UDbjDw',
    appId: '1:947082443040:web:78a221774aef7253be3f45',
    messagingSenderId: '947082443040',
    projectId: 'student-task-manager-2b073',
    authDomain: 'student-task-manager-2b073.firebaseapp.com',
    storageBucket: 'student-task-manager-2b073.firebasestorage.app',
    measurementId: 'G-YDBT4LNQP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA65SNlGqXjVe7Af-ltksOnxuj7vXShorA',
    appId: '1:947082443040:android:da06d314ff9b1581be3f45',
    messagingSenderId: '947082443040',
    projectId: 'student-task-manager-2b073',
    storageBucket: 'student-task-manager-2b073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD65kVS-frOqBeTv92wkn9iLB_BDgGsa6E',
    appId: '1:947082443040:ios:c6e1398ddb7733efbe3f45',
    messagingSenderId: '947082443040',
    projectId: 'student-task-manager-2b073',
    storageBucket: 'student-task-manager-2b073.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD65kVS-frOqBeTv92wkn9iLB_BDgGsa6E',
    appId: '1:947082443040:ios:c6e1398ddb7733efbe3f45',
    messagingSenderId: '947082443040',
    projectId: 'student-task-manager-2b073',
    storageBucket: 'student-task-manager-2b073.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQlqUciBbKX8xb506OGBzarNOz6UDbjDw',
    appId: '1:947082443040:web:6c746d5153c288bebe3f45',
    messagingSenderId: '947082443040',
    projectId: 'student-task-manager-2b073',
    authDomain: 'student-task-manager-2b073.firebaseapp.com',
    storageBucket: 'student-task-manager-2b073.firebasestorage.app',
    measurementId: 'G-GS1G7BSWHX',
  );
}
